### ISSUE TITLE
BUG: reST section headings do not render

### ISSUE THREAD

**Issue by victorlin** [sphinx-doc/sphinx-argparse#31]
### Description

reStructuredText headings do not render, and result in a `CRITICAL` build warning when run in nitpicky (`-n`) mode.

### Steps to reproduce

1. Create a file `sample.py`:

    ```py
    import argparse


    def main():
        parser = argparse.ArgumentParser(
            description="""
    This is a section title
    -----------------------

    `I'm a link <http://www.google.com>`__
    """
        )
        parser.add_argument('cmd', help='execute a `command`')
        return parser

    ```

2. Create a file `index.rst`:

    ```rst
    .. argparse::
       :filename: sample.py
       :func: main
    ```

3. Create a file `conf.py`:

    ```py
    extensions = [
        'sphinx.ext.autodoc',
        'sphinxarg.ext',
    ]
    ```

4. Build it with nitpicky mode (`sphinx-build . _build -n`).
5. Note this warning in the output:

    ```
    None:3: CRITICAL: Unexpected section title.

    This is a section title
    -----------------------
    ```

Built HTML shows the link but not the section title:

![preview](https://user-images.githubusercontent.com/13424970/213575252-1e92d183-0d72-4010-bc56-dc247e505a0d.png)

**Comment by ashb** [comment]
I don't think this will really be fixable, it's tied in to how the sections get generated, sorry.

If someone can PR to fix this we'll review it, but right now this is a "sorry, wontfix"
