### ISSUE TITLE
Potential move to @sphinx-doc

### ISSUE THREAD

**Issue by AA-Turner** [sphinx-doc/sphinx-argparse#41]
Hi @ashb,

Would you consider moving this repo to https://github.com/sphinx-doc?

Projects such as https://github.com/pytest-dev/ & https://github.com/tox-dev/ have started to move to hosting extensions in the main organisation, and from a maintenence perspective it may be easier if the core Sphinx team are able to help!

Thanks,
Adam

**Comment by ashb** [comment]
Sure! What's the process?

**Comment by AA-Turner** [comment]
I've invited you to the Sphinx org to enable the transfer -- it should then be done via this repo's settings page: https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

Please could you also then add me as a package owner on PyPI? 'AA-Turner' 

A

**Comment by AA-Turner** [comment]
Hi @ashb -- were you able to have a look at this?

If helpful, I can put together a more detailed guide for transferring with screenshots etc.

Thanks,
Adam

**Comment by ashb** [comment]
@AA-Turner Done! (Finally!.)
