### ISSUE TITLE
Python `__version__` does not match package release version

### ISSUE THREAD

**Issue by djhoese** [sphinx-doc/sphinx-argparse#42]
https://github.com/ashb/sphinx-argparse/blob/bf1429aa0a4c51ae63d8d6baca0c163a5c6a3a64/sphinxarg/__init__.py#L1C5-L1C5

This is not in sync with the released version of 0.4.0. Perhaps this should be included as part of the release process? Or maybe dynamic version numbers? I don't have experience with poetry to know how hard that is (only setuptools experience).

**Comment by ashb** [comment]
If poetry doesn't do this easily, we could move to hatch/hatchling. I'm not precious about sticking with poetry (poetry I find great for applications, I'm less sold on it for libraries)
