### ISSUE TITLE
Specify function arguments to get parser

### ISSUE THREAD

**Issue by tdegeus** [sphinx-doc/sphinx-argparse#46]
For organizational purposes (that have to do with 'overloading' in the research code, details not important), I would like to do:
```python
import argparse

def myfunction(return_parser_and_quit: bool = False):
    parser = argparse.ArgumentParser()
    # ...

    if return_parser_and_quit: 
        return parser
```
such that the documentation would be something like
```rst
.. argparse::
    :module: foo
    :prog: myfunction
    :func: myfunction
    :kwargs: "return_parser_and_quit = True" 
```
(or whatever other convenient syntax)

**Comment by ashb** [comment]
This seems very niche, and the ability to create args is limited/difficult to do securely 

I would suggest you create a function for doc purposes that calls your function with the requested args
